version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd instagram-batch-3 && cd Instagram/ && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=asif
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=instabackend
    ports:
      - "5432:5432"
  
volumes:
  postgres_data:
